/*
 * Copyright (C) ARRIS Solutions Inc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Christopher Simonson <chris.simonson@arris.com>, July 2016
 */
package automatedaudit;


import java.awt.Color;
import java.awt.GridLayout;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.LinkedList;
import javax.swing.BorderFactory;
import javax.swing.BoxLayout;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.border.TitledBorder;

/**
 * This class is used to create the initial data display GUI.
 * 
 * @author Christopher Simonson
 * @version 1.0
 * @since 2016-07-01
 */
public class A6_InitialDataDisplayGUI extends javax.swing.JFrame {

    private final A8_ExpandedSemUI expandedSemUI;
    private final A8_ExpandedTmxUI expandedTmxUI;
    private final A8_ExpandedEncUI expandedEncUI;
    private LinkedList semList, tmxList, encList;
    String fileLocation;
    
    A6_InitialDataDisplayGUI currDisplay;
    
    /**
     * Creates new form DataDisplay
     * @param location The file location
     */
    public A6_InitialDataDisplayGUI(String location) {
        /* Initializes components */
        initComponents();
        /* Sets the file location */
        fileLocation = location;
        expandedSemUI = new A8_ExpandedSemUI(this);
        expandedTmxUI = new A8_ExpandedTmxUI(this);
        expandedEncUI = new A8_ExpandedEncUI(this);
        /* Sets the layouts of each panel */
        displayPanelTMX.setLayout(new GridLayout(0, 2, 5, 5));
        displayPanelSEM.setLayout(new GridLayout(0, 2, 5, 5));
        displayPanelENC.setLayout(new GridLayout(0, 4, 4, 3));
        displayPanelMUX.setLayout(new GridLayout(3,1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        displayPanelTMX = new javax.swing.JPanel();
        displayPanelENC = new javax.swing.JPanel();
        displayPanelSEM = new javax.swing.JPanel();
        displayPanelMUX = new javax.swing.JPanel();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(6);
        setSize(new java.awt.Dimension(0, 0));

        displayPanelTMX.setBorder(javax.swing.BorderFactory.createTitledBorder("TMX Data"));
        displayPanelTMX.setLayout(new javax.swing.BoxLayout(displayPanelTMX, javax.swing.BoxLayout.LINE_AXIS));

        displayPanelENC.setBorder(javax.swing.BorderFactory.createTitledBorder("Encoder Data"));
        displayPanelENC.setLayout(new javax.swing.BoxLayout(displayPanelENC, javax.swing.BoxLayout.LINE_AXIS));

        displayPanelSEM.setBorder(javax.swing.BorderFactory.createTitledBorder("SEM Data"));
        displayPanelSEM.setLayout(new javax.swing.BoxLayout(displayPanelSEM, javax.swing.BoxLayout.LINE_AXIS));

        displayPanelMUX.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MUX Data", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        displayPanelMUX.setLayout(new javax.swing.BoxLayout(displayPanelMUX, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanelENC, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayPanelMUX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(displayPanelTMX, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(displayPanelSEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayPanelMUX, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(displayPanelTMX, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(displayPanelSEM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(displayPanelENC, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addContainerGap())
        );

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 278, Short.MAX_VALUE)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(398, 446));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Method to run the GUI.
     */ 
    public void runProgram() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A6_InitialDataDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A6_InitialDataDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A6_InitialDataDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A6_InitialDataDisplayGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new A6_InitialDataDisplayGUI(fileLocation).setVisible(false);
        });
    }
    
    /**
     * Method to create Labels for the MUX data.
     * @param muxInput The data to be displayed
     */
    public void displayDataMUX(String muxInput){
        /* Create and initialize a new label */
        JLabel newLabel = new JLabel();
        /* Set the text of the new label */
        newLabel.setText(muxInput);
        /* Adds the label to the panel */
        displayPanelMUX.add(newLabel);
        /* Sets the labels alignement */
        newLabel.setHorizontalAlignment(JLabel.CENTER);
        /* Makes the label visible */
        newLabel.setVisible(true);
    }
    
    /**
     * Method to create Labels for the data.
     * @param input The data to be displayed
     * @param deviceNumber The specific device number
     * @param deviceType The type of device
     * @return The new label created
     */
    public JLabel createLabel(String input, int deviceNumber,
            String deviceType){
        /* Creates an initializes a new label */
        JLabel newLabel = new JLabel();
        /* Sets the text of the new label */
        newLabel.setText(input);
        /* Makes the label clickable for the "name" variable */
        if(deviceNumber >= 1){
            /* Adds a tool tip to label */
            newLabel.setToolTipText("Click to view " + input + " data");
            /* Sets text color to blue */
            newLabel.setForeground(Color.blue);
            /* Adds a mouse listener to label */
            newLabel.addMouseListener(new MouseAdapter(){
                /**
                 * Method to allow the "name" label to be clicked.
                 * @param ev The mouse click event
                 */
                @Override
                public void mouseClicked(MouseEvent ev){
                    /* Checks the device type to ensure labels are place right*/
                    switch (deviceType) {
                        case "SEM":
                            /* Creates a new SEM display object */
                            A7_SEM semData = new A7_SEM(fileLocation);
                            /* Function call to display the Encoder data */
                            semData.displayExpandedSEM(expandedSemUI, semList,
                                    deviceNumber);
                            break;
                        case "TMX":
                            /* Creates a new TMX display object */
                            A7_TMX tmxData = new A7_TMX(fileLocation);
                            /* Function call to display the Encoder data */
                            tmxData.displayExpandedTMX(expandedTmxUI, tmxList, 
                                    deviceNumber);
                            break;
                        case "Encoder":
                            /* Creates a new Encdisplay object */
                            A7_Encoder encData = new A7_Encoder(fileLocation);
                            /* Function call to display the Encoder data */
                            encData.displayExpandedENC(expandedEncUI, encList,
                                    deviceNumber);
                            break;
                        default:
                            break;
                    }
                }
            });
        }
        /* Makes new label visible */
        newLabel.setVisible(true);
        /* Returns the new label created */
        return newLabel;
    }
    
    /**
     * Method to append labels to a panel.
     * @param name The device name label
     * @param type The device type label
     * @param address The device address label
     * @param role The device role
     * @param deviceType The type of device
     */
    public void createPanel(JLabel name, JLabel type, JLabel address, 
            JLabel role, String deviceType){
        /* Creates and initializes a new panel */
        JPanel newPanel = new JPanel();
        /* Sets the layout of the panel */
        newPanel.setLayout(new BoxLayout(newPanel, BoxLayout.Y_AXIS));
        /* Adds the labels to the panel */
        newPanel.add(name);
        newPanel.add(type);
        newPanel.add(address);
        newPanel.add(role);
        /* Adds the panel to the correct device display */
        switch (deviceType) {
            case "TMX":
                /* Adds the panel to the display */
                displayPanelTMX.add(newPanel);
                break;
            case "SEM":
                /* Adds the panel to the display */
                displayPanelSEM.add(newPanel);
                break;
            case "Encoder":
                /* Adds the panel to the display */
                displayPanelENC.add(newPanel);
                break;
            default:
                break;
        }  
        this.pack();
        /* Makes the panel visible */
        newPanel.setVisible(true);
    }
    
    /**
     * Device Linked List Setter.
     * @param list The Device Linked List
     * @param type The type of device
     */
    public void setList(LinkedList list, String type){
        switch (type) {
            case "SEM":
                semList = list;
                break;
            case "TMX":
                tmxList = list;
                break;
            case "ENC":
                encList = list;
                break;
            default:
                break;
        }
    } 
    /**
     * Panel Border Setter.
     * @param borderName The Border Name
     * @param type The type of device
     */
    public void setBorder(String borderName, String type){
        /* Creates and initalizes a new Titled Border */
        TitledBorder title = BorderFactory.createTitledBorder(borderName);
        /* Sets the title to the correct border */
        switch (type) {
            case "SEM":
                /* Sets the border text */
                displayPanelSEM.setBorder(title);
                break;
            case "TMX":
                /* Sets the border text */
                displayPanelTMX.setBorder(title);
                break;
            case "ENC":
                /* Sets the border text */
                displayPanelENC.setBorder(title);
                break;
            default:
                break;
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel displayPanelENC;
    private javax.swing.JPanel displayPanelMUX;
    private javax.swing.JPanel displayPanelSEM;
    private javax.swing.JPanel displayPanelTMX;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
