/*
 * Copyright (C) ARRIS Solutions Inc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Christopher Simonson <chris.simonson@arris.com>, July 2016
 */
package automatedaudit;

/**
 * Class to create a display to view the expanded TMX data.
 * 
 * @author Christopher Simonson
 * @version 1.0
 * @since 
 */
public class A8_ExpandedTmxUI extends javax.swing.JFrame {

    private final A6_InitialDataDisplayGUI prevDisplay;
    
    /**
     * Creates new form ExpandedTmxUI
     * @param pDisplay The previous display
     */
    public A8_ExpandedTmxUI(A6_InitialDataDisplayGUI pDisplay) {
        prevDisplay = pDisplay;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        redundancyGroupLabel = new javax.swing.JLabel();
        encoderGroupLabel = new javax.swing.JLabel();
        redundancyGroupLabelInput = new javax.swing.JLabel();
        encoderGroupLabelInput = new javax.swing.JLabel();
        backupDeviceLabel = new javax.swing.JLabel();
        primaryDeviceLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        osVersionLabel = new javax.swing.JLabel();
        primaryDeviceLabelInput = new javax.swing.JLabel();
        backupDeviceLabelInput = new javax.swing.JLabel();
        versionLabelInput = new javax.swing.JLabel();
        osVersionLabelInput = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        deviceLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        addressLabelInput = new javax.swing.JLabel();
        elementGroupLabel = new javax.swing.JLabel();
        elementGroupLabelInput = new javax.swing.JLabel();
        siteLabel = new javax.swing.JLabel();
        siteLabelInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        redundancyGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        redundancyGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        redundancyGroupLabel.setText("Redundancy Group:");

        encoderGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        encoderGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        encoderGroupLabel.setText("Encoder Group:");

        redundancyGroupLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        redundancyGroupLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        redundancyGroupLabelInput.setText("Group Name");
        redundancyGroupLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        encoderGroupLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encoderGroupLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        encoderGroupLabelInput.setText("Encoder Group");
        encoderGroupLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        backupDeviceLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backupDeviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        backupDeviceLabel.setText("Backup Device:");

        primaryDeviceLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        primaryDeviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        primaryDeviceLabel.setText("Primary Device:");

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLabel.setText("App Version:");

        osVersionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        osVersionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        osVersionLabel.setText("OS Version:");

        primaryDeviceLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        primaryDeviceLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        primaryDeviceLabelInput.setText("Primary");
        primaryDeviceLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        backupDeviceLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        backupDeviceLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        backupDeviceLabelInput.setText("Backup");
        backupDeviceLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        versionLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        versionLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        versionLabelInput.setText("App Version");
        versionLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        osVersionLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        osVersionLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        osVersionLabelInput.setText("OS Version");
        osVersionLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backupDeviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backupDeviceLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(primaryDeviceLabel)
                            .addComponent(osVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(osVersionLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(primaryDeviceLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(redundancyGroupLabel)
                    .addComponent(encoderGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encoderGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redundancyGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redundancyGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redundancyGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encoderGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encoderGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osVersionLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(primaryDeviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(primaryDeviceLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backupDeviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backupDeviceLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        deviceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deviceLabel.setText("DEVICE");

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setText("IP Address:");
        addressLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        addressLabelInput.setText("Ip address");

        elementGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elementGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        elementGroupLabel.setText("Element Group:");
        elementGroupLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        elementGroupLabelInput.setText("Element Group");

        siteLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        siteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        siteLabel.setText("Site:");
        siteLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        siteLabelInput.setText("Site");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(elementGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(siteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(siteLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabelInput)
                    .addComponent(elementGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elementGroupLabelInput)
                    .addComponent(siteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siteLabelInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(269, 269, 269))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.goBack(prevDisplay);
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Method to run the display.
     */
    public void run() {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | 
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(
                    A8_ExpandedTmxUI.class.getName()).log(
                            java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new A8_ExpandedTmxUI(prevDisplay).setVisible(false);
        });
    }
    
    /**
     * Method to bring up the last display.
     * @param prevDisplay The last display
     */
    private void goBack(A6_InitialDataDisplayGUI prevDisplay){
        /* Make previous display visible */
        prevDisplay.setVisible(true);
        /* Make current display invisible */
        this.setVisible(false);  
    }
    
    /**
     * Device Label Setter.
     * @param device The Device
     */
    public void setDeviceLabel(String device){
        deviceLabel.setText(device);
    }
    /**
     * Device IP Address Label Setter.
     * @param address The device IP Address
     */
    public void setAddressLabel(String address){
        addressLabelInput.setText(address);
    }
    /**
     * Device Site Label Setter.
     * @param site The Device Site
     */
    public void setSiteLabel(String site){
        siteLabelInput.setText(site);
    }
    /**
     * Device Element Group Label Setter.
     * @param elementGroup The Device Element Group
     */
    public void setElementGroupLabel(String elementGroup){
        elementGroupLabelInput.setText(elementGroup);
    }
    /**
     * Device Redundancy Group Label Setter.
     * @param redundancyGroup The Device Redundancy Group
     */
    public void setRedundancyGroupLabel(String redundancyGroup){
        redundancyGroupLabelInput.setText(redundancyGroup);
    }
    /**
     * Device Encoder Group Label Setter.
     * @param eGroup The Device Encoder Group
     */
    public void setEncoderGroupLabel(String eGroup){
        encoderGroupLabelInput.setText(eGroup);
    }
    /**
     * Backup Device Label Setter.
     * @param backup The Device Backup
     */
    public void setBackupDeviceLabel(String backup){
        backupDeviceLabelInput.setText(backup);
    }
    /**
     * Primary Device Label Setter.
     * @param primary The Device Primary
     */
    public void setPrimaryDeviceLabel(String primary){
        primaryDeviceLabelInput.setText(primary);
    }
    /**
     * Device APP Version Label Setter.
     * @param version The Device APP Version
     */
    public void setVersionLabel(String version){
        versionLabelInput.setText(version);
    }
    /**
     * Device OS Version Label Setter.
     * @param oVersion The Device OS Version
     */
    public void setOsVersionLabel(String oVersion){
        osVersionLabelInput.setText(oVersion);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabelInput;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel backupDeviceLabel;
    private javax.swing.JLabel backupDeviceLabelInput;
    private javax.swing.JLabel deviceLabel;
    private javax.swing.JLabel elementGroupLabel;
    private javax.swing.JLabel elementGroupLabelInput;
    private javax.swing.JLabel encoderGroupLabel;
    private javax.swing.JLabel encoderGroupLabelInput;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel osVersionLabel;
    private javax.swing.JLabel osVersionLabelInput;
    private javax.swing.JLabel primaryDeviceLabel;
    private javax.swing.JLabel primaryDeviceLabelInput;
    private javax.swing.JLabel redundancyGroupLabel;
    private javax.swing.JLabel redundancyGroupLabelInput;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JLabel siteLabelInput;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionLabelInput;
    // End of variables declaration//GEN-END:variables
}
