/*
 * Copyright (C) ARRIS Solutions Inc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Christopher Simonson <chris.simonson@arris.com>, August 2016
 */
package automatedaudit;

/**
 * Class to create a display to view the expanded SEM data.
 * 
 * @author Christopher Simonson
 * @version 1.0
 * @since 2016-08-01
 */
public class A8_ExpandedEncUI extends javax.swing.JFrame {

    private final A6_InitialDataDisplayGUI prevDisplay;
    private A7_Encoder eData;
    private A8_ExpandedEncUI currDisplay;
    
    /**
     * Creates new form ExpandedEncUI
     * @param pDisplay The previous display
     */
    public A8_ExpandedEncUI(A6_InitialDataDisplayGUI pDisplay) {
        prevDisplay = pDisplay;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        redundancyGroupLabel = new javax.swing.JLabel();
        encoderGroupLabel = new javax.swing.JLabel();
        redundancyGroupLabelInput = new javax.swing.JLabel();
        encoderGroupLabelInput = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        deviceLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        addressLabelInput = new javax.swing.JLabel();
        elementGroupLabel = new javax.swing.JLabel();
        elementGroupLabelInput = new javax.swing.JLabel();
        siteLabel = new javax.swing.JLabel();
        siteLabelInput = new javax.swing.JLabel();
        statMuxButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        redundancyGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        redundancyGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        redundancyGroupLabel.setText("Redundancy Group:");

        encoderGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        encoderGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        encoderGroupLabel.setText("Encoder Group:");

        redundancyGroupLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        redundancyGroupLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        redundancyGroupLabelInput.setText("Group Name");
        redundancyGroupLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        encoderGroupLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encoderGroupLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        encoderGroupLabelInput.setText("Encoder Group");
        encoderGroupLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(redundancyGroupLabel)
                .addGap(4, 4, 4)
                .addComponent(redundancyGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encoderGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(encoderGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(redundancyGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redundancyGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encoderGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encoderGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(82, Short.MAX_VALUE))
        );

        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        deviceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deviceLabel.setText("DEVICE");

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setText("IP Address:");
        addressLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        addressLabelInput.setText("Ip address");

        elementGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elementGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        elementGroupLabel.setText("Element Group:");
        elementGroupLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        elementGroupLabelInput.setText("Element Group");

        siteLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        siteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        siteLabel.setText("Site:");
        siteLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        siteLabelInput.setText("Site");

        statMuxButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statMuxButton.setText("StatMux");
        statMuxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statMuxButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(27, 27, 27)
                        .addComponent(elementGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(siteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(siteLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(deviceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(statMuxButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabelInput)
                    .addComponent(elementGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elementGroupLabelInput)
                    .addComponent(siteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siteLabelInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(statMuxButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(330, 330, 330))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 251, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(575, 311));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.goBack();
    }//GEN-LAST:event_backButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void statMuxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statMuxButtonActionPerformed
        StatMuxDisplay statMux = new StatMuxDisplay(currDisplay);
        statMux.setNumberActiveControllersLabel((String) eData.getDataMap().get(
                "statMuxActiveCtrlr"));
        statMux.setReceiverAddressLabel((String) eData.getDataMap().get("statMuxRecvGroupAddr"));
        statMux.setReceiverPortLabel((String) eData.getDataMap().get("statMuxRecvGroupPort"));
        statMux.setSenderAddressLabel((String) eData.getDataMap().get("statMuxSendGroupAddress"));
        statMux.setSenderPortLabel((String) eData.getDataMap().get("statMuxSendGroupPort"));
        statMux.setMinRateLabel((String) eData.getDataMap().get("statMuxMinVideoTsRate"));
        statMux.setMaxRateLabel((String) eData.getDataMap().get("statMuxMaxVideoTsRate"));
        statMux.runDisplay();
    }//GEN-LAST:event_statMuxButtonActionPerformed

    /**
     * Method to run the GUI display
     */
    public void run() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(A8_ExpandedEncUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(A8_ExpandedEncUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(A8_ExpandedEncUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(A8_ExpandedEncUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new A8_ExpandedEncUI(prevDisplay).setVisible(true);
        });
    }
    
    /**
     * Method to bring up the last display.
     * @param prevDisplay The last display
     */
    private void goBack(){
        /* Make previous display visible */
        prevDisplay.setVisible(true);
        /* Make current display invisible */
        this.setVisible(false);  
    }
    public void setEncoderData(A7_Encoder data){
        eData = data;
    }
    
    /**
     * Device Label Setter.
     * @param device The Device
     */
    public void setDeviceLabel(String device){
        deviceLabel.setText(device);
    }
    /**
     * Device IP Address Label Setter.
     * @param address The device IP Address
     */
    public void setAddressLabel(String address){
        addressLabelInput.setText(address);
    }
    /**
     * Device Site Label Setter.
     * @param site The Device Site
     */
    public void setSiteLabel(String site){
        siteLabelInput.setText(site);
    }
    /**
     * Device Element Group Label Setter.
     * @param elementGroup The Device Element Group
     */
    public void setElementGroupLabel(String elementGroup){
        elementGroupLabelInput.setText(elementGroup);
    }
    /**
     * Device Redundancy Group Label Setter.
     * @param redundancyGroup The Device Redundancy Group
     */
    public void setRedundancyGroupLabel(String redundancyGroup){
        redundancyGroupLabelInput.setText(redundancyGroup);
    }
    /**
     * Device Encoder Group Label Setter.
     * @param eGroup The Device Encoder Group
     */
    public void setEncoderGroupLabel(String eGroup){
        encoderGroupLabelInput.setText(eGroup);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabelInput;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel deviceLabel;
    private javax.swing.JLabel elementGroupLabel;
    private javax.swing.JLabel elementGroupLabelInput;
    private javax.swing.JLabel encoderGroupLabel;
    private javax.swing.JLabel encoderGroupLabelInput;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel redundancyGroupLabel;
    private javax.swing.JLabel redundancyGroupLabelInput;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JLabel siteLabelInput;
    private javax.swing.JButton statMuxButton;
    // End of variables declaration//GEN-END:variables
}
