/*
 * Copyright (C) ARRIS Solutions Inc. - All Rights Reserved
 * Unauthorized copying of this file, via any medium is strictly prohibited
 * Proprietary and confidential
 * Written by Christopher Simonson <chris.simonson@arris.com>, August 2016
 */
package automatedaudit;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;

/**
 * Class to create a display to view the expanded TMX data.
 * 
 * @author Christopher Simonson
 * @version 1.0
 * @since 2016-08-01
 */
public class A8_ExpandedTmxUI extends javax.swing.JFrame {

    private final A6_InitialDataDisplayGUI prevDisplay;
    private A8_ExpandedTmxUI currDisplay;
    
    /**
     * Creates new form ExpandedTmxUI
     * @param pDisplay The previous display
     */
    public A8_ExpandedTmxUI(A6_InitialDataDisplayGUI pDisplay) {
        prevDisplay = pDisplay;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        configPanel = new javax.swing.JPanel();
        redundancyGroupLabel = new javax.swing.JLabel();
        encoderGroupLabel = new javax.swing.JLabel();
        redundancyGroupLabelInput = new javax.swing.JLabel();
        encoderGroupLabelInput = new javax.swing.JLabel();
        deviceStatusLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        osVersionLabel = new javax.swing.JLabel();
        deviceStatusLabelInput = new javax.swing.JLabel();
        versionLabelInput = new javax.swing.JLabel();
        osVersionLabelInput = new javax.swing.JLabel();
        statGroupLabel = new javax.swing.JLabel();
        statGroupDropDown = new javax.swing.JComboBox<>();
        serviceDataLabel = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        deviceLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JButton();
        addressLabel = new javax.swing.JLabel();
        addressLabelInput = new javax.swing.JLabel();
        elementGroupLabel = new javax.swing.JLabel();
        elementGroupLabelInput = new javax.swing.JLabel();
        siteLabel = new javax.swing.JLabel();
        siteLabelInput = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        configPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        redundancyGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        redundancyGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        redundancyGroupLabel.setText("Redundancy Group:");

        encoderGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        encoderGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        encoderGroupLabel.setText("Encoder Group:");

        redundancyGroupLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        redundancyGroupLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        redundancyGroupLabelInput.setText("Group Name");
        redundancyGroupLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        encoderGroupLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        encoderGroupLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        encoderGroupLabelInput.setText("Encoder Group");
        encoderGroupLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        deviceStatusLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        deviceStatusLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        deviceStatusLabel.setText("Primary/Backup ID:");

        versionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLabel.setText("App Version:");

        osVersionLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        osVersionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        osVersionLabel.setText("OS Version:");

        deviceStatusLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        deviceStatusLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deviceStatusLabelInput.setText("Primary/Backup ID");
        deviceStatusLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        versionLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        versionLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        versionLabelInput.setText("App Version");
        versionLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        osVersionLabelInput.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        osVersionLabelInput.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        osVersionLabelInput.setText("OS Version");
        osVersionLabelInput.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        statGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        statGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        statGroupLabel.setText("Stat Group List:");

        serviceDataLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        serviceDataLabel.setForeground(new java.awt.Color(0, 51, 255));
        serviceDataLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        serviceDataLabel.setText("Service Data");

        javax.swing.GroupLayout configPanelLayout = new javax.swing.GroupLayout(configPanel);
        configPanel.setLayout(configPanelLayout);
        configPanelLayout.setHorizontalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(versionLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(deviceStatusLabel)
                            .addComponent(osVersionLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(osVersionLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(deviceStatusLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(serviceDataLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(redundancyGroupLabel)
                            .addComponent(encoderGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(encoderGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(redundancyGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addComponent(statGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(statGroupDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        configPanelLayout.setVerticalGroup(
            configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(configPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(versionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(versionLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redundancyGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redundancyGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(encoderGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(encoderGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osVersionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(osVersionLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(configPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(configPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(deviceStatusLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(deviceStatusLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(statGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, configPanelLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(statGroupDropDown, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(serviceDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        deviceLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        deviceLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        deviceLabel.setText("DEVICE");

        exitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        addressLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        addressLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressLabel.setText("IP Address:");
        addressLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        addressLabelInput.setText("Ip address");

        elementGroupLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        elementGroupLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        elementGroupLabel.setText("Element Group:");
        elementGroupLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        elementGroupLabelInput.setText("Element Group");

        siteLabel.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        siteLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        siteLabel.setText("Site:");
        siteLabel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        siteLabelInput.setText("Site");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(configPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(deviceLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addressLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(elementGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(elementGroupLabelInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(siteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addComponent(siteLabelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deviceLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabelInput)
                    .addComponent(elementGroupLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(elementGroupLabelInput)
                    .addComponent(siteLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(siteLabelInput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(216, 216, 216))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(586, 322));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Action Event Method to go back to previous display.
     * @param evt The Action event.
     */
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        this.goBack(prevDisplay);
    }//GEN-LAST:event_backButtonActionPerformed

    /**
     * Action Event Method to exit the program.
     * @param evt The Action Event.
     */
    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    /**
     * Method to run the display.
     */
    public void run() {
        /* Set the Nimbus look and feel */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : 
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | 
                IllegalAccessException | 
                javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(
                    A8_ExpandedTmxUI.class.getName()).log(
                            java.util.logging.Level.SEVERE, null, ex);
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new A8_ExpandedTmxUI(prevDisplay).setVisible(false);
        });
    }
    
    /**
     * Makes service data text click-able as well function call to run it
     * @param tData The TMX data
     */
    public void serviceDisplay(A7_TMX tData){
        /* Backup file doesn't contain the service info */
        if(tData.getDataMap().get("Role").equals("Backup")){
            serviceDataLabel.setVisible(false);
        }
        else {
            serviceDataLabel.setVisible(true);
            /* Adds a mouse listener to make text click-able */
            serviceDataLabel.addMouseListener(new MouseAdapter(){
                /**
                * Method to create a mouse click event
                * @param ev The mouse click event
                */
                @Override
                public void mouseClicked(MouseEvent ev){
                    /* Creates and initializes a new EMM Dialog Display */
                    A9_ServiceDisplay serviceDialog = 
                            new A9_ServiceDisplay(currDisplay);
                    serviceDialog.setTableRows(tData);
                    /* Function call to run the display */
                    serviceDialog.runServiceDisplay();
                }
            });
        }
    }
    
    /**
     * Method to bring up the last display.
     * @param prevDisplay The last display
     */
    private void goBack(A6_InitialDataDisplayGUI prevDisplay){
        /* Make previous display visible */
        prevDisplay.setVisible(true);
        /* Make current display invisible */
        this.setVisible(false);  
    }
    /**
     * Method to set the data in the STAT Group Drop Down List.
     * @param tData The TMX data
     */
    public void setStatGroupDropDown(A7_TMX tData){
        /* Checks if device is a backup device */
        if(tData.getDataMap().get("Role").equals("Backup")){
            /* Sets Label and Drop down to false since thats for Primary only */
            statGroupLabel.setVisible(false);
            statGroupDropDown.setVisible(false);
        }
        else{
            statGroupLabel.setVisible(true);
            statGroupDropDown.setVisible(true);
            /* Removes any previous items in drop down */
            statGroupDropDown.removeAllItems();
            /* Loops through STAT MUX List */
            for(int i = 1; i <= tData.getStatGroupList().size(); i++){
                /* Creates a key for the hash map */
                String key = "StatGroup.Name" + i;
                /* Adds item to drop down list */
                statGroupDropDown.addItem((String) tData.getDataMap().get(key));
            }
        }
    }
    /**
     * Device Label Setter.
     * @param device The Device
     */
    public void setDeviceLabel(String device){
        deviceLabel.setText(device);
    }
    /**
     * Device IP Address Label Setter.
     * @param address The device IP Address
     */
    public void setAddressLabel(String address){
        addressLabelInput.setText(address);
    }
    /**
     * Device Site Label Setter.
     * @param site The Device Site
     */
    public void setSiteLabel(String site){
        siteLabelInput.setText(site);
    }
    /**
     * Device Element Group Label Setter.
     * @param elementGroup The Device Element Group
     */
    public void setElementGroupLabel(String elementGroup){
        elementGroupLabelInput.setText(elementGroup);
    }
    /**
     * Device Redundancy Group Label Setter.
     * @param redundancyGroup The Device Redundancy Group
     */
    public void setRedundancyGroupLabel(String redundancyGroup){
        redundancyGroupLabelInput.setText(redundancyGroup);
    }
    /**
     * Device Encoder Group Label Setter.
     * @param eGroup The Device Encoder Group
     */
    public void setEncoderGroupLabel(String eGroup){
        encoderGroupLabelInput.setText(eGroup);
    }
    /**
     * Backup Device Label Setter.
     * @param backup The Device Backup
     */
    public void setBackupDeviceLabel(String backup){
        deviceStatusLabel.setText("Backup Device:");
        deviceStatusLabelInput.setText(backup);
    }
    /**
     * Primary Device Label Setter.
     * @param primary The Device Primary
     */
    public void setPrimaryDeviceLabel(String primary){
        deviceStatusLabel.setText("Primary Device:");
        deviceStatusLabelInput.setText(primary);
    }
    /**
     * Device APP Version Label Setter.
     * @param version The Device APP Version
     */
    public void setVersionLabel(String version){
        versionLabelInput.setText(version);
    }
    /**
     * Device OS Version Label Setter.
     * @param oVersion The Device OS Version
     */
    public void setOsVersionLabel(String oVersion){
        osVersionLabelInput.setText(oVersion);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addressLabel;
    private javax.swing.JLabel addressLabelInput;
    private javax.swing.JButton backButton;
    private javax.swing.JPanel configPanel;
    private javax.swing.JLabel deviceLabel;
    private javax.swing.JLabel deviceStatusLabel;
    private javax.swing.JLabel deviceStatusLabelInput;
    private javax.swing.JLabel elementGroupLabel;
    private javax.swing.JLabel elementGroupLabelInput;
    private javax.swing.JLabel encoderGroupLabel;
    private javax.swing.JLabel encoderGroupLabelInput;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel osVersionLabel;
    private javax.swing.JLabel osVersionLabelInput;
    private javax.swing.JLabel redundancyGroupLabel;
    private javax.swing.JLabel redundancyGroupLabelInput;
    private javax.swing.JLabel serviceDataLabel;
    private javax.swing.JLabel siteLabel;
    private javax.swing.JLabel siteLabelInput;
    private javax.swing.JComboBox<String> statGroupDropDown;
    private javax.swing.JLabel statGroupLabel;
    private javax.swing.JLabel versionLabel;
    private javax.swing.JLabel versionLabelInput;
    // End of variables declaration//GEN-END:variables
}
